name: pandoc

on:
  push:
    branches:
      - main
      - fix-*
      - fix/*
      - feat/*
      - feature/*
    paths:
      - image/*
      - Chapter*.md
      - config.yaml
      - crossref.yaml
      - epub.css
      - listing.tex
      - metadata.yaml
      - .github/workflows/pandoc.yaml

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lpi-japan/ossdb-text:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v4
#       - id: list-files
#         run: echo "chapter=$(ls -1 Chapter*.md | grep -v 'Chapter0.md' | sort -V | tr '\n' ' ' | sed 's/ $//')" >> "$GITHUB_OUTPUT"
#       - run: pandoc Chapter0.md -o preface.tex
#       - run: pandoc -d config.yaml --template template.tex -B preface.tex ${{ steps.list-files.outputs.chapter }} -o guide.pdf
      - run: |
          chapter=$(ls -1 Chapter*.md | grep -v 'Chapter0.md' | sort -V | tr '\n' ' ' | sed 's/ $//')
          pandoc Chapter0.md -o preface.tex
          pandoc -d config.yaml --template template.tex -B preface.tex $chapter -o guide.pdf || cat guide.log
      - uses: actions/upload-artifact@v4
        with:
          name: guide.pdf
          path: guide.pdf
  build-epub:
    runs-on: ubuntu-latest
    container:
      image: pandoc/core:3.1.1.0
    steps:
      - uses: actions/checkout@v4
      - id: list-items
        run: cat $(ls -1 Chapter*.md | sort -V | tr '\n' ' ' | sed 's/ $//') | sed 's/^####.*/#& {-}/' > guide.md
        shell: sh
      - run: /usr/bin/awk 'BEGIN{go=0;}{ if (go==1){print;} else {if($$0 ~ /^#/) { go=1;print;}}}' guide.md | pandoc -t epub3 -F pandoc-crossref -o guide.epub -N -M "crossrefYaml=crossref.yaml" --metadata-file=metadata.yaml --epub-cover-image=image/Cover/cover.png --css=epub.css
      - uses: actions/upload-artifact@v4
        with:
          name: guide.epub
          path: guide.epub
